In [4]:
import numpy as np
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline



In [5]:
x_set = np.array([1,2,3,4,5,6])

In [6]:
def f(x) :
    if x in x_set:
        return x / 21
    else:
        return 0

# 확률 변수

In [7]:
X = [x_set, f]

In [8]:
# 확률 p_k를 구한다
prob = np.array([f(x_k) for x_k in x_set])
# x_k와 p_k의 대응을 사전식으로 표시
dict(zip(x_set, prob))

# 1/21, 2/21 이런식으러 나옴

{np.int64(1): 0.048,
 np.int64(2): 0.095,
 np.int64(3): 0.143,
 np.int64(4): 0.190,
 np.int64(5): 0.238,
 np.int64(6): 0.286}

In [ ]:
fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(111)
ax.bar(x_set, prob)
ax.set_xlabel('value')
ax.set_ylabel('probability')

plt.show()

In [10]:
a = {'초콜릿':1, '마카롱':2, '쿠키':3}
a['초콜릿'] = 'One'
a['마카롱'] = 'Two'
a['쿠키'] = 'Tree'
a

{'초콜릿': 'One', '마카롱': 'Two', '쿠키': 'Tree'}

In [11]:
d = dict(초콜릿=20, 마카롱=15, 쿠키=30)
d

{'초콜릿': 20, '마카롱': 15, '쿠키': 30}

In [12]:
key = ['초콜릿', '마카롱', '쿠키']
value = [20,15,30]
d=dict(zip(key,value))
d

{'초콜릿': 20, '마카롱': 15, '쿠키': 30}

In [13]:
d=dict([('초콜릿',20),('마카롱',115),('쿠키',30)])
d

{'초콜릿': 20, '마카롱': 115, '쿠키': 30}

In [15]:
a={'사과':1, '딸기':5, '귤':10}
a

{'사과': 1, '딸기': 5, '귤': 10}

In [16]:
a={('초콜릿', 200):20 ,('마카롱',500):15, ('쿠키',300):30}
a

{('초콜릿', 200): 20, ('마카롱', 500): 15, ('쿠키', 300): 30}

In [17]:
a = {'사과':1, '딸기':5, '귤':10}
v1 = a['딸기']
v1

5

In [18]:
v2 = a['레몬']
v2

KeyError: '레몬'

In [19]:
f1 = '딸기' in a
f1

True

In [20]:
f2 = '레몬' not in a
f2

True

In [21]:
f3 = '레론' in a
f3

False

In [22]:
v1 = a.get('딸기')
v1

5

In [23]:
v2 = a.get('레몬')
v2

In [24]:
np.all(prob >=0)

np.True_

In [25]:
np.sum(prob)

1.000

In [26]:
def F(x):
    return np.sum([f(x_k) for x_k in x_set if x_k <= x])

In [27]:
F(3)

0.286

In [29]:
y_set = np.array([2*x_k+3 for x_k in x_set])
prob = np.array([f(x_k) for x_k in x_set])
dict(zip(y_set, prob))

{np.int64(5): 0.048,
 np.int64(7): 0.095,
 np.int64(9): 0.143,
 np.int64(11): 0.190,
 np.int64(13): 0.238,
 np.int64(15): 0.286}

In [30]:
np.sum([x_k*f(x_k) for x_k in x_set])

4.333

In [31]:
np.random.choice(5, 5, replace=False)

array([2, 3, 0, 4, 1])

In [32]:
np.random.choice(5, 3, replace=False)

array([4, 1, 0])

In [33]:
np.random.choice(5, 10)

array([3, 3, 0, 3, 4, 4, 3, 2, 0, 0])

In [34]:
np.random.choice(5, 10, p=[0.1, 0.0, 0.3, 0.6, 0.0])

array([2, 2, 2, 3, 3, 3, 3, 2, 0, 3])

In [36]:
sample = np.random.choice(x_set, int(1e6), p=prob)
np.mean(sample)

4.333

In [39]:
def E(X, g=lambda x: x):
    x_set, f = X
    return np.sum([g(x_k) * f(x_k) for x_k in x_set])
E(X)

4.333

In [41]:
E(X, g=lambda x: 2*x + 3)

11.667

In [42]:
2* E(X) + 3

11.667

In [43]:
strings = ['hyeja', 'parkhyeja', 'youngtae', 'kimyoungtae', 'bbangtae']

In [44]:
strings.sort(key=lambda x: len(set(list(x))))

In [45]:
strings

['hyeja', 'bbangtae', 'parkhyeja', 'youngtae', 'kimyoungtae']

In [46]:
2*E(X) + 3

11.667

In [47]:
mean = E(X)
np.sum([(x_k-mean)**2 * f(x_k) for x_k in x_set])

2.222

In [48]:
def V(X, g=lambda x: x):
    x_set, f = X
    mean = E(X,g)
    return np.sum([(g(x_k)-mean)**2 * f(x_k) for x_k in x_set])

In [49]:
V(X)

2.222

In [50]:
V(X, lambda x: 2*x + 3)

8.889

In [51]:
2**2 * V(X)

8.889